#!/bin/bash

export DEBIAN_FRONTEND=noninteractive

apt-get update
# Need the force because we already copied /etc/dnsmasq.conf
apt-get install -y -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold" --force-yes dnsmasq
apt-get install -y net-tools

echo "ubuntu:hunter2" | chpasswd
