#!/bin/bash

export DEBIAN_FRONTEND=noninteractive

set -xe

apt-get update
# Need the force because we already copied /etc/dnsmasq.conf
apt-get install -y -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold" --force-yes \
  build-essential \
  dnsmasq \
  git \
  net-tools \
  nginx \
  protobuf-compiler \
  python3-colcon-common-extensions \
  ros-humble-rmw \
  ros-humble-lifecycle-msgs \
  ros-humble-rclcpp \
  ros-humble-rcl-lifecycle \
  ros-humble-rosidl-typesupport-cpp \
  ros-humble-ament-cmake-gtest \
  ros-humble-ament-lint-auto \
  ros-humble-ament-lint-common \
  ros-humble-mimick-vendor \
  ros-humble-performance-test-fixture \
  ros-humble-rcpputils \
  ros-humble-rcutils \
  ros-humble-test-msgs \
  ros-humble-ament-cmake-ros \
  ros-humble-ament-index-cpp \
  ros-humble-builtin-interfaces \
  ros-humble-rcl-interfaces \
  ros-humble-rosgraph-msgs \
  ros-humble-rosidl-runtime-cpp \
  ros-humble-rosidl-typesupport-c \
  ros-humble-libstatistics-collector \
  ros-humble-rcl \
  ros-humble-rcl-yaml-param-parser \
  ros-humble-statistics-msgs \
  ros-humble-tracetools \
  ros-humble-ament-cmake-gmock \
  ros-humble-ament-cmake-google-benchmark \
  ros-humble-rmw-implementation-cmake \
  ros-humble-rosidl-default-generators \
  ros-humble-ament-cmake-gen-version-h \
  python3-dev \
  ros-humble-std-msgs \
  ros-humble-ament-cmake \
  ros-humble-class-loader \
  ros-humble-composition-interfaces \
  ros-humble-launch-testing \
  ros-humble-rosidl-runtime-c \
  ros-humble-action-msgs \
  ros-humble-rcl-action \
  stress-ng \
  sudo \
;

adduser --gecos "" --disabled-password ubuntu
echo "ubuntu:ubuntu" | chpasswd
usermod -a -G adm,audio,cdrom,dialout,dip,floppy,lxd,netdev,plugdev,sudo,video ubuntu

systemctl enable chpassword.service

# So the nginx instance can access the repo
usermod -a -G ubuntu www-data

cd /home/ubuntu

git clone --recursive https://github.com/ros-realtime/roscon-2023-realtime-workshop.git repo

tar cvzf repository.tar.gz repo
mv repository.tar.gz /var/www/html/data

cd repo
source /opt/ros/humble/setup.bash

cd exercise1
colcon build
cd ..

cd exercise2
colcon build
cd ..

cd ..
chown -R ubuntu:ubuntu repo
